name: cafe-f6_documentation
channels:
  - conda-forge
dependencies:
  - black
  - cartopy
  - cftime
  - dask
  - dask-jobqueue
  - eccodes
  - flake8
  - ipykernel
  - jupyterlab
  - matplotlib
  - nb_black
  - nbsphinx
  - nc-time-axis
  - netcdf4
  - pip
  - python=3.9
  - python-cdo
  - sphinx
  - xarray
  - xesmf
  - xskillscore
  - yaml
  - zarr
  - pip:
    - numpydoc
    - pre-commit
    - pydata-sphinx-theme
    - sphinx-autobuild
    - sphinx-autoapi
    - sphinxcontrib.bibtex
    - sphinx-panels
    - sphinx_copybutton
    - xbootstrap
    - -e .
