name:
  "CAFE60v1"
  
path:
  "/g/data/xv83/dcfp/CAFE60v1/"
  
variables:
  atmos_isobaric_month:
    - "t_ref"
    - "precip"
  
normalise:
  precip: 86400
  
rename:
  member: "ensemble"
  
# Functions from src.utils to be applied sequentially to opened dataset
postprocess: 
  truncate_latitudes:
  round_to_start_of_month:
    dim: "time"
  coarsen_monthly_to_annual:
      start_points: ["1960-11-01", "1960-01-01"]
      dim: "time"
  