# Config file for specifying processing using src.data.open_dataset()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.data._open
# path: required
#    The base path of the dataset
# variables: required
#    List of variables to include. For some datasets, the should be further broken
#    into subkeys indicating the realm for each list of variables (e.g. ocean_month). 
#    Non-native variable names can be provided when an appropriate `rename` key is 
#    also provided
# normalise: optional
#    Variable scale factors
# rename: optional
#    Translation between desired variable names and native variable names
# preprocess: optional
#    Functions and kwargs from src.utils to be applied sequentially prior to 
#    concatenation. Only used for datasets comprised of multiple concatenated files
# postprocess: optional
#    Functions and kwargs from src.utils to be applied sequentially to opened dataset

name: "CAFEf6"

path:
  "/g/data/xv83/dcfp/CAFE-f6/"
  
variables:
  atmos_isobaric_month:
    - "t_ref"
    - "precip"
  ocean_month:
    - "sst"
    
rename:
  member: "ensemble"
  
normalise:
  precip: 86400

# Functions from src.utils to be applied sequentially prior to concatenation
preprocess:
  convert_time_to_lead:
  truncate_latitudes:
  coarsen_monthly_to_annual:
    dim: "lead"
  
# Functions from src.utils to be applied sequentially to opened dataset
postprocess: 
  round_to_start_of_month:
    dim: ["init", "time"]