# Config file for specifying processing using src.data.open_dataset()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.data._open
# path: required
#    The base path of the dataset
# variables: required
#    List of variables to include. For some datasets, the should be further broken
#    into subkeys indicating the realm for each list of variables (e.g. ocean_month). 
#    Non-native variable names can be provided when an appropriate `rename` key is 
#    also provided
# normalise: optional
#    Variable scale factors
# rename: optional
#    Translation between desired variable names and native variable names
# preprocess: optional
#    Functions and kwargs from src.utils to be applied sequentially prior to 
#    concatenation. Only used for datasets comprised of multiple concatenated files
# postprocess: optional
#    Functions and kwargs from src.utils to be applied sequentially to opened dataset

name: "CanESM5_hist"

path:
  "/g/data/oi10/replicas/CMIP6/CMIP/CCCma/CanESM5/historical/"
    
variables:
  Amon:
    - "t_ref"
    - "precip"
  Omon:
    - "sst"
    
normalise:
  precip: 86400
  
rename:
  t_ref: "tas"
  precip: "pr"
  sst: "tos"
  
postprocess:
  round_to_start_of_month:
    dim: "time"
  coarsen_monthly_to_annual:
    start_points: ["1960-01-01"]
    dim: "time"