path:
  "/g/data/oi10/replicas/CMIP6/CMIP/CCCma/CanESM5/historical/"
    
rename:
  t_ref: "tas"
  precip: "pr"
  sst: "tos"
  
normalise:
  precip: 86400.0
  
postprocess:
  round_to_start_of_month:
    dim: "time"
  coarsen_monthly_to_annual:
    start_points: ["1960-01-01"]
    dim: "time"