# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:
#   CAFEf6.EN422.annual.anom_1991-2020.ohc300_global.rXY_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.ohc300_global
#     observations: EN422.annual.anom_1991-2020.ohc300_global
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.EN422.4-year.anom_1991-2020.ohc300_global.rXY_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.ohc300_global
#     observations: EN422.4-year.anom_1991-2020.ohc300_global
#     apply:
#       all:
#         mask_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   CAFEf6.EN422.annual.anom_1991-2020.ohc300_global.ri_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.ohc300_global
#     observations: EN422.annual.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.annual.anom_1991-2020.ohc300_global
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.EN422.4-year.anom_1991-2020.ohc300_global.ri_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.ohc300_global
#     observations: EN422.4-year.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.ohc300_global
#     apply:
#       all:
#         mask_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.EN422.annual.anom_1991-2020.ohc300_global.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.ohc300_global
#     observations: EN422.annual.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.annual.anom_1991-2020.ohc300_global
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.EN422.4-year.anom_1991-2020.ohc300_global.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.ohc300_global
#     observations: EN422.4-year.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.ohc300_global
#     apply:
#       all:
#         mask_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05

  CAFEf6.EN422.annual.anom_1991-2020.ohc300_global.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.annual.anom_1991-2020.ohc300_global
    observations: EN422.annual.anom_1991-2020.ohc300_global
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
  CAFEf6.EN422.4-year.anom_1991-2020.ohc300_global.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.4-year.anom_1991-2020.ohc300_global
    observations: EN422.4-year.anom_1991-2020.ohc300_global
    apply:
      all:
        mask_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
#   CAFEf6.EN422.annual.anom_1991-2020.ohc300_global.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.ohc300_global
#     observations: EN422.annual.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.annual.anom_1991-2020.ohc300_global
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.EN422.4-year.anom_1991-2020.ohc300_global.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.ohc300_global
#     observations: EN422.4-year.anom_1991-2020.ohc300_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.ohc300_global
#     apply:
#       all:
#         mask_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05