# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    reference: optional
#        Name of collection in data/processed containing a dataset to baseline against.
#        Alternatively, users can specify "climatology" or "persistence" baselines.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:

  # Global - means - vs HadISST
  # ================================================
  
  CAFEf5.HadISST.annual.anom_1991-2020.sst_global.rXY_1971-2020:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: HadISST.annual.anom_1991-2020.sst_global
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.HadISST.4-year.anom_1991-2020.sst_global.rXY_1971-2020:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: HadISST.4-year.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2020-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf5.HadISST.annual.anom_1991-2020.sst_global.ri_1971-2020:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: HadISST.annual.anom_1991-2020.sst_global
    reference: CAFE_hist.annual.anom_1991-2020.sst_global
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.HadISST.4-year.anom_1991-2020.sst_global.ri_1971-2020:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: HadISST.4-year.anom_1991-2020.sst_global
    reference: CAFE_hist.4-year.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2020-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.HadISST.annual.anom_1991-2020.sst_global.MSSS_hist_1971-2020:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: HadISST.annual.anom_1991-2020.sst_global
    reference: CAFE_hist.annual.anom_1991-2020.sst_global
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.HadISST.4-year.anom_1991-2020.sst_global.MSSS_hist_1971-2020:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: HadISST.4-year.anom_1991-2020.sst_global
    reference: CAFE_hist.4-year.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05

  CAFEf5.HadISST.annual.anom_1991-2020.sst_global.MSSS_clim_1971-2020:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: HadISST.annual.anom_1991-2020.sst_global
    reference: "climatology"
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.HadISST.4-year.anom_1991-2020.sst_global.MSSS_clim_1971-2020:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: HadISST.4-year.anom_1991-2020.sst_global
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.HadISST.annual.anom_1991-2020.sst_global.MSSS_pers_1971-2020:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: HadISST.annual.anom_1991-2020.sst_global
    reference: "persistence"
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.HadISST.4-year.anom_1991-2020.sst_global.MSSS_pers_1971-2020:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: HadISST.4-year.anom_1991-2020.sst_global
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  # Global - means - vs CAFE60
  # ================================================
  
  CAFEf5.CAFE60v1.annual.anom_1991-2020.sst_global.rXY_1971-2019:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: CAFE60v1.annual.anom_1991-2019.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.CAFE60v1.4-year.anom_1991-2020.sst_global.rXY_1971-2019:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: CAFE60v1.4-year.anom_1991-2019.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf5.CAFE60v1.annual.anom_1991-2020.sst_global.ri_1971-2019:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: CAFE60v1.annual.anom_1991-2019.sst_global
    reference: CAFE_hist.annual.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.CAFE60v1.4-year.anom_1991-2020.sst_global.ri_1971-2019:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: CAFE60v1.4-year.anom_1991-2019.sst_global
    reference: CAFE_hist.4-year.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf5.CAFE60v1.annual.anom_1991-2020.sst_global.MSSS_hist_1971-2019:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: CAFE60v1.annual.anom_1991-2019.sst_global
    reference: CAFE_hist.annual.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.CAFE60v1.4-year.anom_1991-2020.sst_global.MSSS_hist_1971-2019:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: CAFE60v1.4-year.anom_1991-2019.sst_global
    reference: CAFE_hist.4-year.anom_1991-2020.sst_global
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05

  CAFEf5.CAFE60v1.annual.anom_1991-2020.sst_global.MSSS_clim_1971-2019:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: CAFE60v1.annual.anom_1991-2019.sst_global
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.CAFE60v1.4-year.anom_1991-2020.sst_global.MSSS_clim_1971-2019:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: CAFE60v1.4-year.anom_1991-2019.sst_global
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.CAFE60v1.annual.anom_1991-2020.sst_global.MSSS_pers_1971-2019:
    hindcast: CAFEf5.annual.anom_1991-2020.sst_global
    observation: CAFE60v1.annual.anom_1991-2019.sst_global
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf5.CAFE60v1.4-year.anom_1991-2020.sst_global.MSSS_pers_1971-2019:
    hindcast: CAFEf5.4-year.anom_1991-2020.sst_global
    observation: CAFE60v1.4-year.anom_1991-2019.sst_global
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1971-01-01", "2019-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05