# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:
#   # Global metrics
#   CAFEf6.GPCP.annual.anom_1991-2020.precip_global.rXY_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_global
#     observations: GPCP.annual.anom_1991-2020.precip_global
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.GPCP.4-year.anom_1991-2020.precip_global.rXY_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_global
#     observations: GPCP.4-year.anom_1991-2020.precip_global
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   CAFEf6.GPCP.annual.anom_1991-2020.precip_global.ri_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_global
#     observations: GPCP.annual.anom_1991-2020.precip_global
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_global
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.GPCP.4-year.anom_1991-2020.precip_global.ri_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_global
#     observations: GPCP.4-year.anom_1991-2020.precip_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_global
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.GPCP.annual.anom_1991-2020.precip_global.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_global
#     observations: GPCP.annual.anom_1991-2020.precip_global
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_global
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.GPCP.4-year.anom_1991-2020.precip_global.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_global
#     observations: GPCP.4-year.anom_1991-2020.precip_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_global
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05

#   CAFEf6.GPCP.annual.anom_1991-2020.precip_global.MSSS_clim_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_global
#     observations: GPCP.annual.anom_1991-2020.precip_global
#     verify:
#       metric: "msss_clim"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.GPCP.4-year.anom_1991-2020.precip_global.MSSS_clim_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_global
#     observations: GPCP.4-year.anom_1991-2020.precip_global
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "msss_clim"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.GPCP.annual.anom_1991-2020.precip_global.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_global
#     observations: GPCP.annual.anom_1991-2020.precip_global
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_global
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.GPCP.4-year.anom_1991-2020.precip_global.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_global
#     observations: GPCP.4-year.anom_1991-2020.precip_global
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_global
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   # Australian NRM region metrics
#   CAFEf6.AGCD.annual.anom_1991-2020.precip_Aus_NRM.rXY_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.annual.anom_1991-2020.precip_Aus_NRM
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.AGCD.4-year.anom_1991-2020.precip_Aus_NRM.rXY_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.4-year.anom_1991-2020.precip_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   CAFEf6.AGCD.annual.anom_1991-2020.precip_Aus_NRM.ri_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.annual.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_Aus_NRM
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.AGCD.4-year.anom_1991-2020.precip_Aus_NRM.ri_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.4-year.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   CAFEf6.AGCD.annual.anom_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.annual.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_Aus_NRM
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.AGCD.4-year.anom_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.4-year.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.AGCD.annual.anom_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.annual.anom_1991-2020.precip_Aus_NRM
#     verify:
#       metric: "msss_clim"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.AGCD.4-year.anom_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.4-year.anom_1991-2020.precip_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "msss_clim"
#       significance: True
#       alpha: 0.05

#   CAFEf6.AGCD.annual.anom_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.annual.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.annual.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.annual.anom_1991-2020.precip_Aus_NRM
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   CAFEf6.AGCD.4-year.anom_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
#     hindcasts: CAFEf6.4-year.anom_1991-2020.precip_Aus_NRM
#     observations: AGCD.4-year.anom_1991-2020.precip_Aus_NRM
#     simulations: CAFE_hist.4-year.anom_1991-2020.precip_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1991-01-01", "2020-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
  # Extreme precipitation
  CAFEf6.AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM.rXY_1991-2020:
    hindcasts: CAFEf6.annual.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM
    verify:
      metric: "acc"
      metric_kwargs:
        correlation: "spearman_r"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM.rXY_1991-2020:
    hindcasts: CAFEf6.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "acc"
      metric_kwargs:
        correlation: "spearman_r"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
    hindcasts: CAFEf6.annual.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.annual.days_over_p90_1991-2020.precip_Aus_NRM
    verify:
      metric: "msss_hist"
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
    hindcasts: CAFEf6.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_hist"
      significance: True
      alpha: 0.05

  CAFEf6.AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.annual.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM
    verify:
      metric: "msss_clim"
      metric_kwargs:
        clim_baseline_value: 0.1
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_clim"
      metric_kwargs:
        clim_baseline_value: 0.1
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
    hindcasts: CAFEf6.annual.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.days_over_p90_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.annual.days_over_p90_1991-2020.precip_Aus_NRM
    verify:
      metric: "crpss"
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
    hindcasts: CAFEf6.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.4-year.days_over_p90_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "crpss"
      significance: True
      alpha: 0.05

  # Drought
  CAFEf6.AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM.rXY_1991-2020:
    hindcasts: CAFEf6.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "acc"
      metric_kwargs:
        correlation: "spearman_r"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM.rXY_1991-2020:
    hindcasts: CAFEf6.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "acc"
      metric_kwargs:
        correlation: "spearman_r"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
    hindcasts: CAFEf6.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_hist"
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM.MSSS_hist_1991-2020:
    hindcasts: CAFEf6.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_hist"
      significance: True
      alpha: 0.05

  CAFEf6.AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_clim"
      metric_kwargs:
        clim_baseline_value: 0.1
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM.MSSS_clim_1991-2020:
    hindcasts: CAFEf6.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss_clim"
      metric_kwargs:
        clim_baseline_value: 0.1
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
    hindcasts: CAFEf6.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.annual.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "crpss"
      significance: True
      alpha: 0.05
      
  CAFEf6.AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM.CRPSS_hist_1991-2020:
    hindcasts: CAFEf6.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    observations: AGCD.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    simulations: CAFE_hist.4-year.3-months_under_p10_1991-2020.precip_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "crpss"
      significance: True
      alpha: 0.05