# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data
#    verify: required
#        arguments to be passed to climpred.HindcastEnsemble.verify()

prepare:
  CAFEf6.JRA55.annual.anom_1991-2020.sst.r_XY:
    hindcasts: CAFEf6.annual.anom_1991-2020.sst
    observations: HadISST.annual.anom_1991-2020.sst
    simulations: CAFE_hist.annual.anom_1991-2020.sst
    verify:
      metric: "pearson_r"
      comparison: "e2o"
      dim: ["init"]
      alignment: "same_verifs"
      reference: "uninitialized"

