# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    reference: optional
#        Name of collection in data/processed containing a dataset to baseline against.
#        Alternatively, users can specify "climatology" or "persistence" baselines.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:

  CAFEf6.HadISST.4-year.anom_1991-2020.ipo.rXY_1991-2020:
    hindcast: CAFEf6.4-year.anom_1991-2020.ipo
    observation: HadISST.4-year.anom_1991-2020.ipo
    apply:
      hindcast:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.HadISST.4-year.anom_1991-2020.ipo.ri_1991-2020:
    hindcast: CAFEf6.4-year.anom_1991-2020.ipo
    observation: HadISST.4-year.anom_1991-2020.ipo
    reference: CAFE_hist.4-year.anom_1991-2020.ipo
    apply:
      hindcast:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.HadISST.4-year.anom_1991-2020.ipo.MSSS_hist_1991-2020:
    hindcast: CAFEf6.4-year.anom_1991-2020.ipo
    observation: HadISST.4-year.anom_1991-2020.ipo
    reference: CAFE_hist.4-year.anom_1991-2020.ipo
    apply:
      hindcast:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05

  CAFEf6.HadISST.4-year.anom_1991-2020.ipo.MSSS_clim_1991-2020:
    hindcast: CAFEf6.4-year.anom_1991-2020.ipo
    observation: HadISST.4-year.anom_1991-2020.ipo
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf6.HadISST.4-year.anom_1991-2020.ipo.MSSS_pers_1991-2020:
    hindcast: CAFEf6.4-year.anom_1991-2020.ipo
    observation: HadISST.4-year.anom_1991-2020.ipo
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05