# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:
  CAFEf6.HadISST.4-year.anom_1991-2020.amv.rXY_1991-2020:
    hindcasts: CAFEf6.index.4-year.anom_1991-2020.amv
    observations: HadISST.index.4-year.anom_1991-2020.amv
    apply:
      all:
        mask_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "acc"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.HadISST.4-year.anom_1991-2020.amv.ri_1991-2020:
    hindcasts: CAFEf6.index.4-year.anom_1991-2020.amv
    observations: HadISST.index.4-year.anom_1991-2020.amv
    simulations: CAFE_hist.index.4-year.anom_1991-2020.amv
    apply:
      all:
        mask_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "acc_initialised"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CAFEf6.HadISST.4-year.anom_1991-2020.amv.MSSS_1991-2020:
    hindcasts: CAFEf6.index.4-year.anom_1991-2020.amv
    observations: HadISST.index.4-year.anom_1991-2020.amv
    simulations: CAFE_hist.index.4-year.anom_1991-2020.amv
    apply:
      all:
        mask_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  CAFEf6.HadISST.4-year.anom_1991-2020.amv.CRPSS_1991-2020:
    hindcasts: CAFEf6.index.4-year.anom_1991-2020.amv
    observations: HadISST.index.4-year.anom_1991-2020.amv
    simulations: CAFE_hist.index.4-year.anom_1991-2020.amv
    apply:
      all:
        mask_period:
          period: ["1991-01-01", "2020-12-31"]
    verify:
      metric: "crpss"
      significance: True
      alpha: 0.05