# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:
  CanESM5.HadISST.annual.anom_1985-2014.sst.rXY_1985-2014:
    hindcasts: CanESM5.annual.anom_1985-2014.sst
    observations: HadISST.annual.anom_1985-2014.sst
    apply:
      all:
        mask_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "acc"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CanESM5.HadISST.4-year.anom_1985-2014.sst.rXY_1985-2014:
    hindcasts: CanESM5.4-year.anom_1985-2014.sst
    observations: HadISST.4-year.anom_1985-2014.sst
    apply:
      all:
        mask_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "acc"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  CanESM5.HadISST.annual.anom_1985-2014.sst.ri_1985-2014:
    hindcasts: CanESM5.annual.anom_1985-2014.sst
    observations: HadISST.annual.anom_1985-2014.sst
    simulations: CanESM5_hist.annual.anom_1985-2014.sst
    apply:
      all:
        mask_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "acc_initialised"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  CanESM5.HadISST.4-year.anom_1985-2014.sst.ri_1985-2014:
    hindcasts: CanESM5.4-year.anom_1985-2014.sst
    observations: HadISST.4-year.anom_1985-2014.sst
    simulations: CanESM5_hist.4-year.anom_1985-2014.sst
    apply:
      all:
        mask_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "acc_initialised"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05