# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    simulations: optional
#        Name of collection in data/processed containing uninitialised simulations.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:
#   # Global metrics
#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_global.rXY_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_global
#     observations: JRA55.annual.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_global.rXY_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_global
#     observations: JRA55.4-year.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_global.ri_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_global
#     observations: JRA55.annual.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_global.ri_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_global
#     observations: JRA55.4-year.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_global.MSSS_hist_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_global
#     observations: JRA55.annual.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_global.MSSS_hist_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_global
#     observations: JRA55.4-year.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05

  EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_global.MSSS_clim_1985-2014:
    hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_global
    observations: JRA55.annual.anom_1985-2014.t_ref_global
    apply:
      all:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
  EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_global.MSSS_clim_1985-2014:
    hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_global
    observations: JRA55.4-year.anom_1985-2014.t_ref_global
    apply:
      all:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_global.CRPSS_hist_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_global
#     observations: JRA55.annual.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_global.CRPSS_hist_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_global
#     observations: JRA55.4-year.anom_1985-2014.t_ref_global
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_global
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   # Australian NRM region metrics
#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_Aus_NRM.rXY_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.annual.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM.rXY_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_Aus_NRM.ri_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.annual.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM.ri_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "acc_initialised"
#       significance: True
#       transform: "Fisher_z"
#       alpha: 0.05

#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_Aus_NRM.MSSS_hist_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.annual.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM.MSSS_hist_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "msss_hist"
#       significance: True
#       alpha: 0.05

  EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_Aus_NRM.MSSS_clim_1985-2014:
    hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_Aus_NRM
    observations: JRA55.annual.anom_1985-2014.t_ref_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
  EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM.MSSS_clim_1985-2014:
    hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_Aus_NRM
    observations: JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM
    apply:
      all:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss_clim"
      significance: True
      alpha: 0.05
      
#   EC_Earth3.JRA55.annual.anom_1985-2014.t_ref_Aus_NRM.CRPSS_hist_1985-2014:
#     hindcasts: EC_Earth3.annual.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.annual.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.annual.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05
      
#   EC_Earth3.JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM.CRPSS_hist_1985-2014:
#     hindcasts: EC_Earth3.4-year.anom_1985-2014.t_ref_Aus_NRM
#     observations: JRA55.4-year.anom_1985-2014.t_ref_Aus_NRM
#     simulations: EC_Earth3_hist.4-year.anom_1985-2014.t_ref_Aus_NRM
#     apply:
#       all:
#         keep_period:
#           period: ["1985-01-01", "2014-12-31"]
#     verify:
#       metric: "crpss"
#       significance: True
#       alpha: 0.05