# Config file for specifying skill assessment using src.verify()
# ==================================================================================

# prepare: required
#    List of unique identifiers for skill metrics to prepare and save. This will 
#    be used to save the prepared skill metric as {identifier}.zarr. Each identifier 
#    can include the following:
#
#    hindcasts: required
#        Name of collection in data/processed containing the hindcasts to assess. 
#    observations: optional
#        Name of collection in data/processed containing the observations.
#    reference: optional
#        Name of collection in data/processed containing a dataset to baseline against.
#        Alternatively, users can specify "climatology" or "persistence" baselines.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to the 
#        input data. Can be applied to all provided datasets using the key `all:`,
#        or to individual datasets using, for example, `hindcasts: <functions>`
#    verify: required
#        Arguments to be passed to src.verify.calculate_metric

prepare:

  # Global - means
  # ================================================
  
  EC_Earth3.GPCP.annual.anom_1985-2014.precip_global.rXY_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_global
    observation: GPCP.annual.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  EC_Earth3.GPCP.4-year.anom_1985-2014.precip_global.rXY_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_global
    observation: GPCP.4-year.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  EC_Earth3.GPCP.annual.anom_1985-2014.precip_global.ri_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_global
    observation: GPCP.annual.anom_1985-2014.precip_global
    reference: EC_Earth3_hist.annual.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  EC_Earth3.GPCP.4-year.anom_1985-2014.precip_global.ri_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_global
    observation: GPCP.4-year.anom_1985-2014.precip_global
    reference: EC_Earth3_hist.4-year.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  EC_Earth3.GPCP.annual.anom_1985-2014.precip_global.MSSS_hist_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_global
    observation: GPCP.annual.anom_1985-2014.precip_global
    reference: EC_Earth3_hist.annual.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.GPCP.4-year.anom_1985-2014.precip_global.MSSS_hist_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_global
    observation: GPCP.4-year.anom_1985-2014.precip_global
    reference: EC_Earth3_hist.4-year.anom_1985-2014.precip_global
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05

  EC_Earth3.GPCP.annual.anom_1985-2014.precip_global.MSSS_clim_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_global
    observation: GPCP.annual.anom_1985-2014.precip_global
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.GPCP.4-year.anom_1985-2014.precip_global.MSSS_clim_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_global
    observation: GPCP.4-year.anom_1985-2014.precip_global
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.GPCP.annual.anom_1985-2014.precip_global.MSSS_pers_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_global
    observation: GPCP.annual.anom_1985-2014.precip_global
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1990-01-01", "2014-12-31"] # GPCP begins 1979, 11 year hindcast
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.GPCP.4-year.anom_1985-2014.precip_global.MSSS_pers_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_global
    observation: GPCP.4-year.anom_1985-2014.precip_global
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1990-01-01", "2014-12-31"] # GPCP begins 1979, 11 year hindcast
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  # NRM regions - means
  # =================================================

  EC_Earth3.AGCD.annual.anom_1985-2014.precip_Aus_NRM.rXY_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.annual.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  EC_Earth3.AGCD.4-year.anom_1985-2014.precip_Aus_NRM.rXY_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.4-year.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "rXY"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  EC_Earth3.AGCD.annual.anom_1985-2014.precip_Aus_NRM.ri_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.annual.anom_1985-2014.precip_Aus_NRM
    reference: EC_Earth3_hist.annual.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05
      
  EC_Earth3.AGCD.4-year.anom_1985-2014.precip_Aus_NRM.ri_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.4-year.anom_1985-2014.precip_Aus_NRM
    reference: EC_Earth3_hist.4-year.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "ri"
      significance: True
      transform: "Fisher_z"
      alpha: 0.05

  EC_Earth3.AGCD.annual.anom_1985-2014.precip_Aus_NRM.MSSS_hist_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.annual.anom_1985-2014.precip_Aus_NRM
    reference: EC_Earth3_hist.annual.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.AGCD.4-year.anom_1985-2014.precip_Aus_NRM.MSSS_hist_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.4-year.anom_1985-2014.precip_Aus_NRM
    reference: EC_Earth3_hist.4-year.anom_1985-2014.precip_Aus_NRM
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05

  EC_Earth3.AGCD.annual.anom_1985-2014.precip_Aus_NRM.MSSS_clim_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.annual.anom_1985-2014.precip_Aus_NRM
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.AGCD.4-year.anom_1985-2014.precip_Aus_NRM.MSSS_clim_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.4-year.anom_1985-2014.precip_Aus_NRM
    reference: "climatology"
    apply:
      hindcast:
        keep_period:
          period: ["1985-01-01", "2014-12-31"]
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.AGCD.annual.anom_1985-2014.precip_Aus_NRM.MSSS_pers_1985-2014:
    hindcast: EC_Earth3.annual.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.annual.anom_1985-2014.precip_Aus_NRM
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1990-01-01", "2014-12-31"] # GPCP begins 1979, 11 year hindcast
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05
      
  EC_Earth3.AGCD.4-year.anom_1985-2014.precip_Aus_NRM.MSSS_pers_1985-2014:
    hindcast: EC_Earth3.4-year.anom_1985-2014.precip_Aus_NRM
    observation: AGCD.4-year.anom_1985-2014.precip_Aus_NRM
    reference: "persistence"
    apply:
      hindcast:
        keep_period:
          period: ["1990-01-01", "2014-12-31"] # GPCP begins 1979, 11 year hindcast
    verify:
      metric: "msss"
      significance: True
      alpha: 0.05