# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "AGCD"

prepare:

  # Prepare drought index over NRM regions
  # ================================================
  
  # 3-month averages
  
  month.full.precip_Aus_NRM:
    uses:
      - "precip"
    apply:
      resample:
        freq: "M"
        start_points: ["1960-01-01"]
        min_samples: 28
      round_to_start_of_month:
        dim: "time"
      convert_calendar:
        calendar: "julian"
      add_area_using_cdo_gridarea:
      average_over_NRM_super_clusters:
      rechunk:
        time: -1
        
  3-month-Jan.full.precip_Aus_NRM:
    uses:
      prepared:
        - "month.full.precip_Aus_NRM"
    apply:
      coarsen:
        window_size: 3
        start_points: ["1960-01-01"]
        dim: "time"
      rechunk:
        time: -1
        
  3-month-Nov.full.precip_Aus_NRM:
    uses:
      prepared:
        - "month.full.precip_Aus_NRM"
    apply:
      coarsen:
        window_size: 3
        start_points: ["1960-11-01"]
        dim: "time"
      rechunk:
        time: -1
        
  # Annual 3-month averages under p10 - 1991-2020 climatology

  annual-Jan.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "3-month-Jan.full.precip_Aus_NRM"
    apply:
      under_percentile_threshold:
        percentile: 0.1
        percentile_period: ["1991-01-01", "2020-12-31"]
        frequency: "month"
      coarsen:
        window_size: 4
        start_points: ["1960-03-01"] # First 3-month mean for Jan forecast is Mar
        dim: "time"
      rechunk:
        time: -1
        
  annual-Nov.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "3-month-Nov.full.precip_Aus_NRM"
    apply:
      under_percentile_threshold:
        percentile: 0.1
        percentile_period: ["1991-01-01", "2020-12-31"]
        frequency: "month"
      coarsen:
        window_size: 4
        start_points: ["1961-01-01"] # First 3-month mean for Nov forecast is Jan
        dim: "time"
      rechunk:
        time: -1
        
  annual.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Jan.3-months_under_p10_1991-2020.precip_Aus_NRM"
        - "annual-Nov.3-months_under_p10_1991-2020.precip_Aus_NRM"
    apply:
      rechunk:
        time: -1
        
  # Annual 3-month averages under p10 - 1985-2014 climatology

  annual-Jan.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "3-month-Jan.full.precip_Aus_NRM"
    apply:
      under_percentile_threshold:
        percentile: 0.1
        percentile_period: ["1985-01-01", "2014-12-31"]
        frequency: "month"
      coarsen:
        window_size: 4
        start_points: ["1960-03-01"] # First 3-month mean for Jan forecast is Mar
        dim: "time"
      rechunk:
        time: -1
        
  annual-Nov.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "3-month-Nov.full.precip_Aus_NRM"
    apply:
      under_percentile_threshold:
        percentile: 0.1
        percentile_period: ["1985-01-01", "2014-12-31"]
        frequency: "month"
      coarsen:
        window_size: 4
        start_points: ["1961-01-01"] # First 3-month mean for Nov forecast is Jan
        dim: "time"
      rechunk:
        time: -1
        
  annual.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Jan.3-months_under_p10_1985-2014.precip_Aus_NRM"
        - "annual-Nov.3-months_under_p10_1985-2014.precip_Aus_NRM"
    apply:
      rechunk:
        time: -1
        
  # 4-year 3-month averages under p10 - 1991-2020 climatology
        
  4-year-Jan.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Jan.3-months_under_p10_1991-2020.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        
  4-year-Nov.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Nov.3-months_under_p10_1991-2020.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        
  4-year.3-months_under_p10_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "4-year-Jan.3-months_under_p10_1991-2020.precip_Aus_NRM"
        - "4-year-Nov.3-months_under_p10_1991-2020.precip_Aus_NRM"
    apply:
      rechunk:
        time: -1
        
  # 4-year 3-month averages under p10 - 1985-2014 climatology
        
  4-year-Jan.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Jan.3-months_under_p10_1985-2014.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        
  4-year-Nov.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "annual-Nov.3-months_under_p10_1985-2014.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        
  4-year.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "4-year-Jan.3-months_under_p10_1985-2014.precip_Aus_NRM"
        - "4-year-Nov.3-months_under_p10_1985-2014.precip_Aus_NRM"
    apply:
      rechunk:
        time: -1