# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFEf5"

prepare:
#   annual.full.t_ref_global:
#     uses:
#       atmos_isobaric_month:
#         - "t_ref"
#     apply:
#       truncate_latitudes:
#       add_CAFE_grid_info:
#       rename:
#         names: 
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.precip_global:
#     uses:
#       atmos_isobaric_month:
#         - "precip"
#     apply:
#       truncate_latitudes:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       convert:
#         conversion:
#           precip:
#             multiply_by: 86400
#       normalise_by_days_in_month:
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}

  annual.full.slp_global:
    uses:
      atmos_isobaric_month:
        - "slp"
    apply:
      truncate_latitudes:
      add_CAFE_grid_info:
      rename:
        names:
          ensemble: "member"
          init_date: "init"
          lead_time: "lead"
      add_attrs:
        attrs: {"units": "months"}
        variable: "lead"
      convert:
        conversion:
          slp:
            multiply_by: 100
      coarsen:
        window_size: 12
        dim: "lead"
      round_to_start_of_month:
        dim: ["init", "time"]
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.sst_global:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.ohc300_global:
#     uses:
#       ocean_month:
#         - "temp"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           st_ocean: "depth"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       convert:
#         conversion:
#           temp:
#             add: 273.15
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       calculate_ohc300:
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   3-month.full.nino34:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           area_t: "area"
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       calculate_nino34:
#       coarsen:
#         window_size: 3
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   3-month.full.dmi:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           area_t: "area"
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       calculate_dmi:
#       coarsen:
#         window_size: 3
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   3-month.anom_1991-2020.sam:
#     uses:
#       atmos_isobaric_month:
#         - "slp"
#     apply:
#       truncate_latitudes:
#       rename:
#         names: 
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       calculate_sam:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         groupby_dim: "init"
#       coarsen:
#         window_size: 3
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   3-month.anom_1991-2020.nao:
#     uses:
#       atmos_isobaric_month:
#         - "slp"
#     apply:
#       truncate_latitudes:
#       rename:
#         names: 
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       calculate_nao:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         groupby_dim: "init"
#       coarsen:
#         window_size: 3
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   # Prepare anomalies from prepared datasets
#   annual.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual.full.t_ref_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.precip_global:
#     uses:
#       prepared:
#         - "annual.full.precip_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}

  annual.anom_1991-2020.slp_global:
    uses:
      prepared:
        - "annual.full.slp_global"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual.full.sst_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.ohc300_global:
#     uses:
#       prepared:
#         - "annual.full.ohc300_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}

#   3-month.anom_1991-2020.nino34:
#     uses:
#       prepared:
#         - "3-month.full.nino34"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   3-month.anom_1991-2020.dmi:
#     uses:
#       prepared:
#         - "3-month.full.dmi"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   # Prepare 4-year-averages from prepared datasets
#   4-year.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual.anom_1991-2020.t_ref_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#         dim: "lead"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   4-year.anom_1991-2020.precip_global:
#     uses:
#       prepared:
#         - "annual.anom_1991-2020.precip_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#         dim: "lead"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}

  4-year.anom_1991-2020.slp_global:
    uses:
      prepared:
        - "annual.anom_1991-2020.slp_global"
    apply:
      rolling_mean:
        window_size: 4
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   4-year.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual.anom_1991-2020.sst_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#         dim: "lead"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   4-year.anom_1991-2020.ohc300_global:
#     uses:
#       prepared:
#         - "annual.anom_1991-2020.ohc300_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#         dim: "lead"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}

#   # Prepare AMV, IPO from prepared datasets
#   4-year.anom_1991-2020.amv:
#     uses:
#       prepared:
#         - "4-year.anom_1991-2020.sst"
#     apply:
#       calculate_amv:
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}
        
#   4-year.anom_1991-2020.ipo:
#     uses:
#       prepared:
#         - "4-year.anom_1991-2020.sst"
#     apply:
#       calculate_ipo:
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1}