# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFE_hist"

prepare:

  # Prepare anomalies over globe
  # ================================================

  # Annual average
  
  annual.full.precip_global:
    uses:
      atmos_isobaric_month:
        - "precip"
    apply:
      rename:
        ensemble: "member"
      convert:
        precip:
          multiply_by: 86400
      truncate_latitudes:
      round_to_start_of_month:
        dim: "time"
      normalise_by_days_in_month:
      coarsen:
        window_size: 12
        start_points: ["1960-11-01"]
        dim: "time"
      rechunk:
        time: -1
        member: -1
        lat: 10
        lon: 12
  
  # Annual anomalies - 1991-2020 climatology
  
  annual.anom_1991-2020.precip_global:
    uses:
      prepared:
        - "annual.full.precip_global"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
        frequency: "month"
      rechunk:
        time: -1
        member: -1
        lat: 10
        lon: 12

  # 4-year anomalies - 1991-2020 climatology
  
  4-year.anom_1991-2020.precip_global:
    uses:
      prepared:
        - "annual.anom_1991-2020.precip_global"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        member: -1
        lat: 10
        lon: 12

  # Prepare anomalies over NRM regions
  # ================================================
  
  # Annual average

  annual.full.precip_Aus_NRM:
    uses:
      atmos_isobaric_month:
        - "precip"
    apply:
      rename:
        ensemble: "member"
      convert:
        precip:
          multiply_by: 86400
      truncate_latitudes:
      round_to_start_of_month:
        dim: "time"
      normalise_by_days_in_month:
      coarsen:
        window_size: 12
        start_points: ["1960-11-01"]
        dim: "time"
      average_over_NRM_super_clusters:
      rechunk:
        time: -1
        member: -1
        
  # Annual anomalies - 1991-2020 climatology
        
  annual.anom_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.full.precip_Aus_NRM"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
        frequency: "month"
      rechunk:
        time: -1
        member: -1
        
  # 4-year anomalies - 1991-2020 climatology
        
  4-year.anom_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.anom_1991-2020.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        member: -1

  # Prepare days over p90 over NRM regions
  # ================================================

  # Daily
  
  daily.full.precip_Aus_NRM:
    uses:
      atmos_isobaric_daily:
        - "precip"
    apply:
      convert_calendar:
        calendar: "noleap"
      rename:
        ensemble: "member"
      truncate_latitudes:
      convert:
        precip:
          multiply_by: 86400
      round_to_start_of_day:
        dim: "time"
      average_over_NRM_super_clusters:
      rechunk:
        time: -1
        member: -1
        
  # Annual days over p90 - 1991-2020 climatology
        
  annual.days_over_p90_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "daily.full.precip_Aus_NRM"
    apply:
      over_percentile_threshold:
        percentile: 0.9
        percentile_period: ["1991-01-01", "2020-12-31"]
        frequency: "dayofyear"
      coarsen:
        window_size: 365
        start_points: ["1960-11-01"]
        dim: "time"
      round_to_start_of_month:
        dim: "time"
      rechunk:
        time: -1
        member: -1
        
  # 4-year days over p90 - 1991-2020 climatology
        
  4-year.days_over_p90_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.days_over_p90_1991-2020.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
        dim: "time"
      rechunk:
        time: -1
        member: -1
    