# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFE_hist"

prepare:

  # Prepare Excess Heat Factor over Australia
  # ================================================

  # Daily bias-corrected t_ref
  
  daily.abc_1991-2020.t_ref_Aus:
    uses:
      atmos_isobaric_daily:
        - "t_ref"
    apply:
      convert_calendar:
        calendar: "noleap"
      extract_lon_lat_box:
        box: [110, 155, -45, -9]
        weighted_average: False
      rename:
        ensemble: "member"
      truncate_latitudes:
      convert:
        t_ref:
          add: -273.15
      round_to_start_of_day:
        dim: "time"
      correct_bias:
        obsv_file: "data/processed/AGCD.daily.full.t_ref_Aus.zarr"
        period: ["1991-01-01", "2020-12-31"]
        frequency: "dayofyear"
        method: "additive"
      rechunk:
        time: 365
        member: -1
        
  # Daily EHF severity
  
  daily.full.ehf_severity_Aus:
    uses:
      prepared:
        - "daily.abc_1991-2020.t_ref_Aus"
    apply:
      calculate_EHF_severity:
        T_p95_file: "data/processed/AGCD.daily.p95_1971-2000.t_ref_Aus.zarr"
        EHF_p85_file: "data/processed/AGCD.daily.p85_1958-2011.ehf_Aus.zarr"
      rechunk:
        time: 365
        member: -1
        
  # Annual days over 0
  
  annual.days_over_0.ehf_severity_Aus:
    uses:
      prepared:
        - "daily.full.ehf_severity_Aus"
    apply:
      greater_than:
        value: 0
      coarsen:
        window_size: 365
        start_points: ["1960-11-01"]
        dim: "time"
      round_to_start_of_month:
        dim: "time"
      rechunk:
        time: -1
        member: -1
        
  # 4-year days over 0
  
  4-year.days_over_0.ehf_severity_Aus:
    uses:
      prepared:
        - "annual.days_over_0.ehf_severity_Aus"
    apply:
      rolling_mean:
        window_size: 4
        dim: "time"
      rechunk:
        time: -1
        member: -1