# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFEf5"

prepare:
#   annual.full.t_ref:
#     uses:
#       atmos_isobaric_month:
#         - "t_ref"
#     apply:
#       truncate_latitudes:
#       add_CAFE_grid_info:
#       rename:
#         names: 
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#         variable: "lead"
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.precip:
#     uses:
#       atmos_isobaric_month:
#         - "precip"
#     apply:
#       truncate_latitudes:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#       add_attrs:
#         attrs: {"units": "months"}
#       convert:
#         conversion:
#           precip:
#             multiply_by: 86400
#       normalise_by_days_in_month:
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.sst:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.full.ohc300:
#     uses:
#       ocean_month:
#         - "temp"
#     apply:
#       add_CAFE_grid_info:
#       rename:
#         names:
#           ensemble: "member"
#           init_date: "init"
#           lead_time: "lead"
#           xt_ocean: "x"
#           yt_ocean: "y"
#           st_ocean: "depth"
#           geolon_t: "lon"
#           geolat_t: "lat"
#       add_attrs:
#         attrs: {"units": "months"}
#       convert:
#         conversion:
#           temp:
#             add: 273.15
#       coarsen:
#         window_size: 12
#         dim: "lead"
#       round_to_start_of_month:
#         dim: ["init", "time"]
#       calculate_ohc300:
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   # Prepare anomalies from prepared datasets
#   annual.anom_1991-2020.t_ref:
#     uses:
#       prepared:
#         - "annual.full.t_ref"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.precip:
#     uses:
#       prepared:
#         - "annual.full.precip"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.sst:
#     uses:
#       prepared:
#         - "annual.full.sst"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
#   annual.anom_1991-2020.ohc300:
#     uses:
#       prepared:
#         - "annual.full.ohc300"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rechunk:
#         chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
  # Prepare 4-year-averages from prepared datasets
  4-year.anom_1991-2020.t_ref:
    uses:
      prepared:
        - "annual.anom_1991-2020.t_ref"
    apply:
      coarsen:
        window_size: 4 
        start_points: [23,]
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
  4-year.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual.anom_1991-2020.precip"
    apply:
      coarsen:
        window_size: 4 
        start_points: [23,]
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
  4-year.anom_1991-2020.sst:
    uses:
      prepared:
        - "annual.anom_1991-2020.sst"
    apply:
      coarsen:
        window_size: 4 
        start_points: [23,]
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}
        
  4-year.anom_1991-2020.ohc300:
    uses:
      prepared:
        - "annual.anom_1991-2020.ohc300"
    apply:
      coarsen:
        window_size: 4 
        start_points: [23,]
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1, "lat": 10, "lon": 12}