# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFEf6"

prepare:
  annual.full.t_ref_Aus_NRM:
    uses:
      atmos_isobaric_month:
        - "t_ref"
    preprocess:
      convert_time_to_lead:
        time_freq: "months"
      truncate_latitudes:
      coarsen:
        window_size: 12
        dim: "lead"
    apply:
      rename:
        names: 
          ensemble: "member"
      round_to_start_of_month:
        dim: ["init", "time"]
      average_over_NRM_super_clusters:
      mask_CAFEf6_reduced_dt:
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  annual.full.precip_Aus_NRM:
    uses:
      atmos_isobaric_month:
        - "precip"
    preprocess:
      normalise_by_days_in_month:
      convert_time_to_lead:
        time_freq: "months"
      truncate_latitudes:
      coarsen:
        window_size: 12
        dim: "lead"
    apply:
      rename:
        names:
          ensemble: "member"
      convert:
        conversion:
          precip:
            multiply_by: 86400
      round_to_start_of_month:
        dim: ["init", "time"]
      average_over_NRM_super_clusters:
      mask_CAFEf6_reduced_dt:
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  annual.full.V_tot_Aus_NRM:
    uses:
      atmos_isobaric_month:
        - "u_ref"
        - "v_ref"
    preprocess:
      convert_time_to_lead:
        time_freq: "months"
      truncate_latitudes:
    apply:
      calculate_wind_speed:
        u_name: "u_ref"
        v_name: "v_ref"
      coarsen:
        window_size: 12
        dim: "lead"
      rename:
        names: 
          ensemble: "member"
      round_to_start_of_month:
        dim: ["init", "time"]
      average_over_NRM_super_clusters:
      mask_CAFEf6_reduced_dt:
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  # Prepare anomalies from prepared datasets
  annual.anom_1991-2020.t_ref_Aus_NRM:
    uses:
      prepared:
        - "annual.full.t_ref_Aus_NRM"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  annual.anom_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.full.precip_Aus_NRM"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  annual.anom_1991-2020.V_tot_Aus_NRM:
    uses:
      prepared:
        - "annual.full.V_tot_Aus_NRM"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  # Prepare 4-year-averages from prepared datasets
  4-year.anom_1991-2020.t_ref_Aus_NRM:
    uses:
      prepared:
        - "annual.anom_1991-2020.t_ref_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4 
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  4-year.anom_1991-2020.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.anom_1991-2020.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4 
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  4-year.anom_1991-2020.V_tot_Aus_NRM:
    uses:
      prepared:
        - "annual.anom_1991-2020.V_tot_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4 
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}

  #  Extremes
  daily.full.t_ref_max_Aus_NRM:
    uses:
      atmos_isobaric_daily:
        - "t_ref_max"
    preprocess:
      drop_Feb_29:
      convert_time_to_lead:
        time_freq: "days"
      truncate_latitudes:
    apply:
      rename:
        names: 
          ensemble: "member"
      convert:
        conversion:
          t_ref_max:
            add: -273.15
      average_over_NRM_super_clusters:
      mask_CAFEf6_reduced_dt:
      rechunk:
        chunks: {"init": -1, "lead": 28, "member": -1}
        
  annual.days_over_p90.t_ref_max_Aus_NRM:
    uses:
      prepared:
        - "daily.full.t_ref_max_Aus_NRM"
    apply:
      over_percentile_threshold:
        percentile: 0.9
        percentile_period: ["1991-01-01", "2020-12-31"]
      coarsen:
        window_size: 365
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}
        
  4-year.days_over_p90.t_ref_max_Aus_NRM:
    uses:
      prepared:
        - "annual.days_over_p90.t_ref_max_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
        dim: "lead"
      rechunk:
        chunks: {"init": -1, "lead": 1, "member": -1}