# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CAFE60v1"

prepare:

  # Prepare anomalies
  # ================================================
        
  # 3-month anomalies - 1991-2020 climatology
  
  3-month.anom_1991-2020.nao:
    uses:
      atmos_isobaric_month:
        - "slp"
    apply:
      truncate_latitudes:
      rename:
        ensemble: "member"
      round_to_start_of_month:
        dim: "time"
      calculate_nao:
        clim_period: ["1991-01-01", "2020-12-31"]
      rolling_mean:
        window_size: 3
        start_points: ["1960-11-01"]
        dim: "time"
      rechunk:
        time: -1
        member: -1