# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "CanESM5"

prepare:

  # Prepare drought index over NRM regions
  # ================================================
  
  # 3-month averages
  
  3-month.full.precip_Aus_NRM:
    uses:
      Amon:
        - "pr"
    apply:
      rename:
        pr: "precip"
        areacella: "area"
      convert:
        precip:
          multiply_by: 86400
      coarsen:
        window_size: 3
        dim: "lead"
      average_over_NRM_super_clusters:
      rechunk:
        init: -1
        lead: 1
        member: -1
        
  # Annual 3-month averages under p10 - 1985-2014 climatology

  annual.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "3-month.full.precip_Aus_NRM"
    apply:
      under_percentile_threshold:
        percentile: 0.1
        percentile_period: ["1985-01-01", "2014-12-31"]
        frequency: "month"
      coarsen:
        window_size: 4
        dim: "lead"
      rechunk:
        init: -1
        lead: 1
        member: -1

  # 4-year 3-month averages under p10 - 1985-2014 climatology

  4-year.3-months_under_p10_1985-2014.precip_Aus_NRM:
    uses:
      prepared:
        - "annual.3-months_under_p10_1985-2014.precip_Aus_NRM"
    apply:
      rolling_mean:
        window_size: 4
        dim: "lead"
      rechunk:
        init: -1
        lead: 1
        member: -1