# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "EC_Earth3_hist"

prepare:
  annual.full.t_ref:
    uses:
      Amon:
        - "tas"
    apply:
      rename:
        names: 
          tas: "t_ref"
      round_to_start_of_month:
        dim: "time"
      coarsen_monthly_to_annual:
        start_points: ["1960-11-01"]
        dim: "time"
      force_to_Julian_calendar:
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}
        
  annual.full.precip:
    uses:
      Amon:
        - "pr"
    apply:
      rename:
        names: 
          pr: "precip"
      convert:
        conversion:
          precip:
            multiply_by: 86400
      round_to_start_of_month:
        dim: "time"
      coarsen_monthly_to_annual:
        start_points: ["1960-11-01"]
        dim: "time"
      force_to_Julian_calendar:
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}
      
  annual.full.sst:
    uses:
      Omon:
        - "tos"
    apply:
      rename:
        names: 
          tos: "sst"
          i: "x"
          j: "y"
          longitude: "lon"
          latitude: "lat"
      round_to_start_of_month:
        dim: "time"
      coarsen_monthly_to_annual:
        start_points: ["1960-11-01"]
        dim: "time"
      force_to_Julian_calendar:
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}

  # Prepare anomalies from prepared datasets
  annual.anom_1985-2014.t_ref:
    uses:
      prepared:
        - "annual.full.t_ref"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}
        
  annual.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual.full.precip"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}
        
  annual.anom_1985-2014.sst:
    uses:
      prepared:
        - "annual.full.sst"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        chunks: {"time": -1, "member": -1, "lat": 10, "lon": 12}