# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "EN422"

prepare:
  annual-Jan.full.ohc300_global:
    uses:
      - "temperature"
    apply:
      rename:
        temperature: "temp"
      round_to_start_of_month:
        dim: "time"
      force_to_Julian_calendar:
      coarsen:
        window_size: 12
        start_points: ["1960-01-01"]
        dim: "time"
      calculate_ohc300:
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual-Nov.full.ohc300_global:
    uses:
      - "temperature"
    apply:
      rename:
        temperature: "temp"
      round_to_start_of_month:
        dim: "time"
      force_to_Julian_calendar:
      coarsen:
        window_size: 12
        start_points: ["1960-11-01"]
        dim: "time"
      calculate_ohc300:
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  # Prepare anomalies from prepared datasets      
  annual-Jan.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.full.ohc300_global"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual-Nov.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "annual-Nov.full.ohc300_global"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.anom_1991-2020.ohc300_global"
        - "annual-Nov.anom_1991-2020.ohc300_global"
    apply:
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual-Jan.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.full.ohc300_global"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual-Nov.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "annual-Nov.full.ohc300_global"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  annual.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.anom_1985-2014.ohc300_global"
        - "annual-Nov.anom_1985-2014.ohc300_global"
    apply:
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  # Prepare 4-year-averages from prepared datasets
  4-year-Jan.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.anom_1991-2020.ohc300_global"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  4-year-Nov.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "annual-Nov.anom_1991-2020.ohc300_global"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  4-year.anom_1991-2020.ohc300_global:
    uses:
      prepared:
        - "4-year-Jan.anom_1991-2020.ohc300_global"
        - "4-year-Nov.anom_1991-2020.ohc300_global"
    apply:
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  4-year-Jan.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "annual-Jan.anom_1985-2014.ohc300_global"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  4-year-Nov.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "annual-Nov.anom_1985-2014.ohc300_global"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        time: -1
        lat: 10
        lon: 12
        
  4-year.anom_1985-2014.ohc300_global:
    uses:
      prepared:
        - "4-year-Jan.anom_1985-2014.ohc300_global"
        - "4-year-Nov.anom_1985-2014.ohc300_global"
    apply:
      rechunk:
        time: -1
        lat: 10
        lon: 12