# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "GPCP"

prepare:
  annual-Jan.full.precip:
    uses:
      - "precip"
    apply:
      rename:
        names: 
          latitude: "lat"
          longitude: "lon"
      force_to_Julian_calendar:
      coarsen:
        window_size: 12
        start_points: ["1979-01-01"]
        dim: "time"
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  annual-Nov.full.precip:
    uses:
      - "precip"
    apply:
      rename:
        names: 
          latitude: "lat"
          longitude: "lon"
      force_to_Julian_calendar:
      coarsen:
        window_size: 12
        start_points: ["1979-11-01"]
        dim: "time"
      interpolate_to_grid_from_file:
        file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  # Prepare anomalies from prepared datasets
  annual-Jan.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual-Jan.full.precip"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
    
  annual-Nov.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual-Nov.full.precip"
    apply:
      anomalise:
        clim_period: ["1991-01-01", "2020-12-31"]
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  annual.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual-Jan.anom_1991-2020.precip"
        - "annual-Nov.anom_1991-2020.precip"
    apply:
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  annual-Jan.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual-Jan.full.precip"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  annual-Nov.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual-Nov.full.precip"
    apply:
      anomalise:
        clim_period: ["1985-01-01", "2014-12-31"]
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  annual.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual-Jan.anom_1985-2014.precip"
        - "annual-Nov.anom_1985-2014.precip"
    apply:
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  # Prepare 4-year-averages from prepared datasets
  4-year-Jan.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual-Jan.anom_1991-2020.precip"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  4-year-Nov.anom_1991-2020.precip:
    uses:
      prepared:
        - "annual-Nov.anom_1991-2020.precip"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  4-year.anom_1991-2020.precip:
    uses:
      prepared:
        - "4-year-Jan.anom_1991-2020.precip"
        - "4-year-Nov.anom_1991-2020.precip"
    apply:
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  4-year-Jan.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual-Jan.anom_1985-2014.precip"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  4-year-Nov.anom_1985-2014.precip:
    uses:
      prepared:
        - "annual-Nov.anom_1985-2014.precip"
    apply:
      rolling_mean:
        window_size: 4
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}
        
  4-year.anom_1985-2014.precip:
    uses:
      prepared:
        - "4-year-Jan.anom_1985-2014.precip"
        - "4-year-Nov.anom_1985-2014.precip"
    apply:
      rechunk:
        chunks: {"time": -1, "lat": 10, "lon": 12}