# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "HadISST"

prepare:
#   annual-Jan.full.sst_global:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       rename:
#         latitude: "lat"
#         longitude: "lon"
#       round_to_start_of_month:
#         dim: "time"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-01-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   annual-Nov.full.sst_global:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       rename:
#         latitude: "lat"
#         longitude: "lon"
#       round_to_start_of_month:
#         dim: "time"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-11-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   3-month.full.nino34:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       rename:
#         latitude: "lat"
#         longitude: "lon"
#       round_to_start_of_month:
#         dim: "time"
#       convert_calendar:
#         calendar: "julian"
#       add_area_using_cdo_gridarea:
#       calculate_nino34:
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1
        
#   3-month.full.dmi:
#     uses:
#       ocean_month:
#         - "sst"
#     apply:
#       rename:
#         latitude: "lat"
#         longitude: "lon"
#       round_to_start_of_month:
#         dim: "time"
#       convert_calendar:
#         calendar: "julian"
#       add_area_using_cdo_gridarea:
#       calculate_dmi:
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1
        
#   # Prepare anomalies from prepared datasets
#   annual-Jan.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.sst_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.sst_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.sst_global"
#         - "annual-Nov.anom_1991-2020.sst_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Jan.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.sst_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.sst_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.sst_global"
#         - "annual-Nov.anom_1985-2014.sst_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   3-month.anom_1991-2020.nino34:
#     uses:
#       prepared:
#         - "3-month.full.nino34"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
        
#   3-month.anom_1985-2014.nino34:
#     uses:
#       prepared:
#         - "3-month.full.nino34"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
        
#   3-month.anom_1991-2020.dmi:
#     uses:
#       prepared:
#         - "3-month.full.dmi"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
        
#   3-month.anom_1985-2014.dmi:
#     uses:
#       prepared:
#         - "3-month.full.dmi"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
        
#   # Prepare 4-year-averages from prepared datasets
#   4-year-Jan.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.sst_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Nov.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1991-2020.sst_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1991-2020.sst_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1991-2020.sst_global"
#         - "4-year-Nov.anom_1991-2020.sst_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Jan.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.sst_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12}
        
#   4-year-Nov.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1985-2014.sst_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1985-2014.sst_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1985-2014.sst_global"
#         - "4-year-Nov.anom_1985-2014.sst_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   # Prepare AMV, IPO from prepared datasets
#   4-year.anom_1991-2020.amv:
#     uses:
#       prepared:
#         - "4-year.anom_1991-2020.sst"
#     apply:
#       calculate_amv:
#       rechunk:
#         time: -1
        
#   4-year.anom_1985-2014.amv:
#     uses:
#       prepared:
#         - "4-year.anom_1985-2014.sst"
#     apply:
#       calculate_amv:
#       rechunk:
#         time: -1
        
#   4-year.anom_1991-2020.ipo:
#     uses:
#       prepared:
#         - "4-year.anom_1991-2020.sst"
#     apply:
#       calculate_ipo:
#       rechunk:
#         time: -1
        
#   4-year.anom_1985-2014.ipo:
#     uses:
#       prepared:
#         - "4-year.anom_1985-2014.sst"
#     apply:
#       calculate_ipo:
#       rechunk:
#         time: -1