# Config file for specifying processing using src.prepare_data()
# ==================================================================================

# name: required
#    The name of the dataset. Must match a method in src.prepare_data._open
#
# prepare: required
#    List of unique identifiers for output variables to prepare and save. This will 
#    be used to save the prepared output variable(s) as {name}.{identifier}.zarr. 
#    Each identifier can include the following:
#
#    uses: required
#        List of input variables required to compute the output variable(s). For 
#        some datasets, this should be further broken into subkeys indicating the 
#        realm for each list of variables (e.g. ocean_month). Alternatively, users 
#        can provide the identifier of a previously prepared dataset by entering
#        `prepared: <identifier>`.
#    preprocess: optional
#        Functions and kwargs from src.utils to be applied sequentially prior to 
#        concatenation (for datasets comprised of multiple concatenated files) 
#        and/or prior to merging input variables from multiple realms where more 
#        than one are specified.
#    apply: optional
#        Functions and kwargs from src.utils to be applied sequentially to opened 
#        (and concatenated/merge, where appropriate) dataset.

name: "JRA55"

prepare:
#   annual-Jan.full.t_ref_global:
#     uses:
#       surface_month:
#         - "TMP_GDS0_HTGL"
#     apply:
#       rename:
#         TMP_GDS0_HTGL: "t_ref"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-01-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.full.t_ref_global:
#     uses:
#       surface_month:
#         - "TMP_GDS0_HTGL"
#     apply:
#       rename:
#         TMP_GDS0_HTGL: "t_ref"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-11-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   annual-Jan.full.slp_global:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-01-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.full.slp_global:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       coarsen:
#         window_size: 12
#         start_points: ["1960-11-01"]
#         dim: "time"
#       interpolate_to_grid_from_file:
#         file: "data/raw/gridinfo/CAFE_atmos_grid.nc"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   3-month.anom_1991-2020.sam:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       calculate_sam:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1
        
#   3-month.anom_1985-2014.sam:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       calculate_sam:
#         clim_period: ["1985-01-01", "2014-12-31"]
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1

#   3-month.anom_1991-2020.nao:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       calculate_nao:
#         clim_period: ["1991-01-01", "2020-12-31"]
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1
        
#   3-month.anom_1985-2014.nao:
#     uses:
#       surface_month:
#         - "PRMSL_GDS0_MSL"
#     apply:
#       rename:
#         PRMSL_GDS0_MSL: "slp"
#         initial_time0_hours: "time"
#         g0_lat_1: "lat"
#         g0_lon_2: "lon"
#       convert_calendar:
#         calendar: "julian"
#       calculate_nao:
#         clim_period: ["1985-01-01", "2014-12-31"]
#       rolling_mean:
#         window_size: 3
#         start_points: ["1960-01-01"]
#         dim: "time"
#       rechunk:
#         time: -1
        
#   # Prepare anomalies from prepared datasets
#   annual-Jan.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.t_ref_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.t_ref_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.t_ref_global"
#         - "annual-Nov.anom_1991-2020.t_ref_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Jan.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.t_ref_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.t_ref_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.t_ref_global"
#         - "annual-Nov.anom_1985-2014.t_ref_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   annual-Jan.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.slp_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.slp_global"
#     apply:
#       anomalise:
#         clim_period: ["1991-01-01", "2020-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.slp_global"
#         - "annual-Nov.anom_1991-2020.slp_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Jan.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.full.slp_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual-Nov.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "annual-Nov.full.slp_global"
#     apply:
#       anomalise:
#         clim_period: ["1985-01-01", "2014-12-31"]
#         frequency: "month"
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   annual.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.slp_global"
#         - "annual-Nov.anom_1985-2014.slp_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
           
#   # Prepare 4-year-averages from prepared datasets
#   4-year-Jan.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.t_ref_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Nov.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1991-2020.t_ref_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1991-2020.t_ref_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1991-2020.t_ref_global"
#         - "4-year-Nov.anom_1991-2020.t_ref_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Jan.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.t_ref_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Nov.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1985-2014.t_ref_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1985-2014.t_ref_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1985-2014.t_ref_global"
#         - "4-year-Nov.anom_1985-2014.t_ref_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12

#   4-year-Jan.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1991-2020.slp_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Nov.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1991-2020.slp_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1991-2020.slp_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1991-2020.slp_global"
#         - "4-year-Nov.anom_1991-2020.slp_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Jan.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "annual-Jan.anom_1985-2014.slp_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year-Nov.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "annual-Nov.anom_1985-2014.slp_global"
#     apply:
#       rolling_mean:
#         window_size: 4
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12
        
#   4-year.anom_1985-2014.slp_global:
#     uses:
#       prepared:
#         - "4-year-Jan.anom_1985-2014.slp_global"
#         - "4-year-Nov.anom_1985-2014.slp_global"
#     apply:
#       rechunk:
#         time: -1
#         lat: 10
#         lon: 12